FROM zookeeper:3.5

# Maintainer information
LABEL author="Adam Baldwin <adam@dec1pher.com>"

# Meta data about the docker image
LABEL project="zookeeper"
LABEL name="zookeeper"
LABEL description="zookeeper dev server."

COPY container/zoo.cfg /conf/

EXPOSE 2181 2888 3888 8080
