version: '3.7'

services:
  kafka-dev:
    container_name: kafka-dev
    image: ab/kafka-zookeeper
    build:
      context: .
      dockerfile: ./Dockerfile.kafka
    environment:
      BROKER_ID: 0
      PLAINTEXT_PORT: 9092
      SSL_PORT: 9192
      SASL_SSL_PORT: 9292
      ZK_HOST: zk-dev
      HOST_ROLE: kafka
    ports:
      - "9092:9092"
    tty: true
  zk-dev:
    container_name: zk-dev
    image: ab/kafka-zookeeper
    build:
      context: .
      dockerfile: ./Dockerfile.kafka
    environment:
      HOST_ROLE: zookeeper
    ports:
      - "2181:2181"
    tty: true
  redis-dev:
    container_name: redis-dev
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - type: bind
        source: /home/underride/IdeaProjects/csv-transform-parser/bin/data
        target: /test-data
    command: redis-server --appendonly yes
    tty: true
  mysql-dev:
    container_name: mysql-dev
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "The mysql password."
    ports:
      - "3306:3306"
      - "33060:33060"
    tty: true